name: build_nexus

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install ldid

      - name: Setup Theos
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip -d $THEOS/sdks
          mv $THEOS/sdks/sdks-master/* $THEOS/sdks
          rm -rf master.zip $THEOS/sdks/sdks-master

      - name: Build NEXUS
        run: |
          export THEOS=~/theos
          make clean all

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: nexus_v1.0
          path: .theos/obj/arm64/nexus.dylib
